In [22]:
import pandas as pd
import collections
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
from scipy.stats import pearsonr

In [17]:
# Read in the data from the Excel file
dispListLara = pd.read_excel('dispersionLara.xlsx')
dispListSod = pd.read_excel('dispersionSod.xlsx')
dispListSam = pd.read_excel('dispersionSam.xlsx')

,Words,Frequency,DpNorm,Da,Sam AoA,Normed AoA,Production AoA,Concreteness,Session 1,Session 2,...,Session 52,Session 53,Session 54,Session 55,Session 56,Session 57,Session 58,Session 59,Unnamed: 67,Unnamed: 68
0,you,7371,0.149662,0.218413,16.0,17.0,25.0,4.11,92,173,...,62,129,124,138,186,63,133,60,7370,NaN
1,be,7355,0.158712,0.224172,NaN,NaN,NaN,1.85,158,165,...,64,161,98,91,123,29,97,45,7355,NaN
2,a,3656,0.255619,0.346988,NaN,NaN,28.0,1.46,82,24,...,38,68,15,32,43,12,40,7,3656,NaN
3,yeah,3294,0.206423,0.304549,NaN,NaN,NaN,1.89,60,85,...,43,139,57,41,90,27,70,29,3294,NaN
4,the,3225,0.182422,0.262284,NaN,NaN,28.0,1.43,67,61,...,35,75,45,54,54,29,70,38,3225,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2333,worst,1,0.981758,1.000000,NaN,NaN,NaN,1.54,0,0,...,0,0,0,0,0,0,0,0,1,NaN
2334,wound,1,0.984487,1.000000,NaN,NaN,NaN,4.24,0,0,...,0,0,0,0,0,0,0,0,1,NaN
2335,write,1,0.981251,1.000000,NaN,NaN,28.0,4.22,0,0,...,0,0,0,0,0,0,0,0,1,NaN
2336,yelling,1,0.981758,1.000000,NaN,NaN,NaN,4.08,0,0,...,0,0,0,0,0,0,0,0,1,NaN
2337,zoom,1,0.980813,1.000000,NaN,NaN,NaN,3.10,0,0,...,0,0,0,0,0,0,0,0,1,NaN

In [15]:
# Merge the dataframes dispListLara, dispListSod, and dispListSam based on the common column 'Words'. 
# This creates a dataframe with only the words all three corpora have in common
common_words = pd.merge(dispListLara, dispListSod, on='Words', how='inner')
common_words = pd.merge(common_words, dispListSam, on='Words', how='inner')

# Select the required columns
common_words = common_words[['Words', 'DPNorm_x', 'DPNorm_y', 'DpNorm']]
common_words.columns = ['Words', 'DPNorm_Lara', 'DPNorm_Sod', 'DPNorm_Sam']

# # Print the common_words dataframe
print(common_words)

        Words  DPNorm_Lara  DPNorm_Sod  DPNorm_Sam
0           a     0.077838    0.111599    0.255619
1       about     0.219108    0.273363    0.291863
2       achoo     0.957929    0.716899    0.987772
3      across     0.826084    0.964084    0.839575
4    actually     0.408817    0.961740    0.506808
..        ...          ...         ...         ...
827  yourself     0.478999    0.766934    0.430814
828       yum     0.499418    0.542772    0.890416
829     yummy     0.589840    0.425440    0.534290
830     zebra     0.912815    0.957901    0.922719
831      zoom     0.937387    0.844846    0.980813

[832 rows x 4 columns]

In [1]:
dpnorm_scores = common_words[['DPNorm_Lara', 'DPNorm_Sod', 'DPNorm_Sam']]

# Calculate the correlation matrix of DPNorm across all three corpora
correlation_matrix = dpnorm_scores.corr()

# Print the correlation matrix
print(correlation_matrix)

NameError: name 'common_words' is not defined